const SUPPLIES_TEXT = {
  SUPPLIES: 'Komponenty',
  SUPPLIES_COUNTER_TITLE: 'Licznik komponentów',

  SUPPLIES_BASIC_COUNTER_INPUT_FIELD_TEXT: 'Ilość',

  SUPPLIES_CARDBOARD_COUNTER_INPUT_FIELD_TEXT: 'Ilość kartonów',
  SUPPLIES_CARDBOARD_COUNTER_ADDITIONAL_INPUT_BEFORE_TEXT: 'jeden karton = ',
  SUPPLIES_CARDBOARD_COUNTER_ADDITIONAL_INPUT_AFTER_TEXT: 'szt',
};

export { SUPPLIES_TEXT };
