const GUMS_TEXT = {
  GUMS: 'Uszczelka',
  GUMS_COUNTER_TITLE: 'Licznik gumy',

  GUMS_BASIC_COUNTER_INPUT_FIELD_TEXT: 'Ilość gumy w kg',

  GUMS_CARDBOARD_COUNTER_INPUT_FIELD_TEXT: 'Ilość kartonów',
  GUMS_CARDBOARD_COUNTER_ADDITIONAL_INPUT_BEFORE_TEXT: 'jeden karton = ',
  GUMS_CARDBOARD_COUNTER_ADDITIONAL_INPUT_AFTER_TEXT: 'kg',
};

export { GUMS_TEXT };
