const PIGMENTS_TEXT = {
  PIGMENTS: 'Pigmenty',
  PIGMENTS_COUNTER_TITLE: 'Licznik pigmentu',

  PIGMENTS_BASIC_COUNTER_INPUT_FIELD_TEXT: 'Ilość pigmentu w kg',

  PIGMENTS_BAGS_COUNTER_INPUT_FIELD_TEXT: 'Ilość worków',
  PIGMENTS_BAGS_COUNTER_ADDITIONAL_INPUT_BEFORE_TEXT: 'Waga jednego worku = ',
  PIGMENTS_BAGS_COUNTER_ADDITIONAL_INPUT_AFTER_TEXT: 'kg',

  PIGMENTS_CONTAINER_COUNTER_INPUT_FIELD_TEXT: 'Waga kontenera z pigmentem',
  PIGMENTS_CONTAINER_COUNTER_ADDITIONAL_INPUT_BEFORE_TEXT: 'Waga kontenera = ',
  PIGMENTS_CONTAINER_COUNTER_ADDITIONAL_INPUT_AFTER_TEXT: 'kg',
};

export { PIGMENTS_TEXT };
