const CHEMISTRY_TEXT = {
  CHEMISTRY: 'Chemia',
  CHEMISTRY_COUNTER_TITLE: 'Licznik chemii',
  CHEMISTRY_VENEER: 'Okleina',
  CHEMISTRY_EXTRUSION: 'Ekstruzja',
  CHEMISTRY_BASIC_COUNTER_INPUT_FIELD_TEXT: 'Ilość chemii w szt',
};

export { CHEMISTRY_TEXT };
